import { FieldValue } from "firebase-admin/firestore";
import { db } from "../../db/firestore";
import { findVisibleCategories } from "../categories/categories.repository";
import { fromCents, toCents } from "../../utils/money";
import { invalidateTransactionReads, memoizeReads } from "../../utils/readCache";

export type SplitType = "none" | "equal" | "proportional" | "by_category" | "custom";
export type TransactionType = "expense" | "income";
// How it was actually paid -- independent of which PAR account it's booked on
// and of parcelamento (a card purchase in 1x is still "credit"). Optional:
// older transactions and ones generated by debts/faturas/etc. leave it null.
export const PAYMENT_METHODS = ["credit", "debit", "pix", "cash"] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export interface TransactionRow {
  id: string;
  groupId: string;
  accountId: string;
  accountType: "personal" | "joint";
  accountOwnerId: string | null;
  categoryId: string | null;
  payerId: string;
  createdBy: string;
  description: string;
  amount: string;
  transactionType: TransactionType;
  occurredAt: string;
  isPrivate: boolean;
  splitType: SplitType;
  paymentMethod: PaymentMethod | null;
  // Set only on transactions generated as part of a recurring series (a
  // subscription, rent, salary...). recurringGroupId is the id of the first
  // occurrence in the series (shared by every occurrence, including that
  // first one); recurringIndex/recurringTotal locate it within the series
  // (e.g. 3 of 12). Plain one-off transactions leave all three null.
  recurringGroupId: string | null;
  recurringIndex: number | null;
  recurringTotal: number | null;
  // Only meaningful when splitType !== "none" -- whether the other
  // member(s)' share has actually been settled up outside the app (a Pix,
  // cash...). Purely a manual status flag toggled from the extrato; it
  // doesn't touch amountCents or the transaction's real effect on the
  // account balance either way.
  isSettled: boolean;
  // Id of the real income transaction created when this was marked settled
  // (see transactions.service.ts setSplitSettledForUser) -- same
  // linked-transaction pattern used by debts/cards/shopping: "paid" isn't
  // just a flag, it's backed by a real entry in the ledger, deleted again
  // if the split is reopened. Null while isSettled is false.
  settlementTransactionId: string | null;
  // Set only on money moved into/out of a cartão com limite garantido
  // ("Guardar mais"/"Resgatar") -- a transfer, not spending: it changes the
  // account balance (the money really left the account) but is skipped by
  // every income/expense total, so reports and budgets don't count parking
  // money in the card as a gasto. Owned by the card: deleting the card
  // deletes these too, and they can't be edited/deleted on their own.
  securedCardId: string | null;
  // Preenchido só em dinheiro emprestado / recebido de volta pelos
  // Empréstimos -- uma transferência como o securedCardId acima: mexe no
  // saldo, nunca conta como gasto/receita. Pertence ao empréstimo
  // (editado/excluído só por ele).
  loanId: string | null;
  // Outras transferências (mexem no saldo, nunca contam como gasto/receita):
  // "goal" = dinheiro guardado numa meta ou retirado dela (goalId; só a tela
  // Metas desfaz); "accounts" = entre as suas contas (cada extrato traz o seu
  // lado, então o saldo de cada conta bate com o banco).
  transferKind: TransferKind | null;
  goalId: string | null;
  // Lançamento criado por outra tela (fatura paga, parcela de dívida,
  // reembolso de despesa dividida, item da lista de compras). Quem é dono
  // dele é essa tela: apagar ou mudar o valor por aqui deixaria a fatura
  // "paga" sem o dinheiro ter saído. Null nos lançamentos normais (e nos
  // antigos, de antes desse campo -- ver isLinkedTransaction no service).
  linkKind: LinkKind | null;
}

export type TransferKind = "goal" | "accounts";

export const LINK_KINDS = ["card_statement", "debt_installment", "settlement", "shopping"] as const;
export type LinkKind = (typeof LINK_KINDS)[number];

// Transferências movem dinheiro entre a conta e outro lugar (um cartão
// garantido, alguém que te deve) sem ser receita nem gasto.
export function isTransferData(data: FirebaseFirestore.DocumentData): boolean {
  return Boolean(data.securedCardId || data.loanId || data.transferKind);
}

export interface TransactionListRow extends TransactionRow {
  categoryName: string | null;
  categoryEmoji: string | null;
}

const transactionsCol = db.collection("transactions");

function toTransactionRow(doc: FirebaseFirestore.DocumentSnapshot): TransactionRow {
  const data = doc.data()!;
  return {
    id: doc.id,
    groupId: data.groupId,
    accountId: data.accountId,
    accountType: data.accountType,
    accountOwnerId: data.accountOwnerId ?? null,
    categoryId: data.categoryId ?? null,
    payerId: data.payerId,
    createdBy: data.createdBy,
    description: data.description,
    amount: fromCents(data.amountCents),
    transactionType: data.transactionType,
    occurredAt: data.occurredAt,
    isPrivate: data.isPrivate,
    splitType: data.splitType,
    paymentMethod: data.paymentMethod ?? null,
    recurringGroupId: data.recurringGroupId ?? null,
    recurringIndex: data.recurringIndex ?? null,
    recurringTotal: data.recurringTotal ?? null,
    isSettled: data.isSettled ?? false,
    settlementTransactionId: data.settlementTransactionId ?? null,
    securedCardId: data.securedCardId ?? null,
    loanId: data.loanId ?? null,
    transferKind: data.transferKind ?? null,
    goalId: data.goalId ?? null,
    linkKind: data.linkKind ?? null,
  };
}

async function loadCategoriesMap(groupId: string): Promise<Map<string, { name: string; emoji: string | null }>> {
  const categories = await findVisibleCategories(groupId);
  return new Map(categories.map((c) => [c.id, { name: c.name, emoji: c.emoji }]));
}

export interface NewTransactionInput {
  groupId: string;
  accountId: string;
  accountType: "personal" | "joint";
  accountOwnerId: string | null;
  categoryId: string | null;
  payerId: string;
  createdBy: string;
  description: string;
  amount: number;
  transactionType: TransactionType;
  occurredAt: string;
  isPrivate: boolean;
  splitType: SplitType;
  paymentMethod?: PaymentMethod | null;
  securedCardId?: string | null;
  loanId?: string | null;
  transferKind?: TransferKind | null;
  goalId?: string | null;
  linkKind?: LinkKind | null;
}

export interface SplitInput {
  userId: string;
  shareAmountCents: number;
}

// O que o lote (batch) e a transação do Firestore têm em comum pra gravar.
interface Writer {
  set(ref: FirebaseFirestore.DocumentReference, data: FirebaseFirestore.DocumentData): unknown;
  delete(ref: FirebaseFirestore.DocumentReference): unknown;
}

function transactionData(
  base: Omit<NewTransactionInput, "occurredAt">,
  occurredAt: string,
  recurring: { groupId: string; index: number; total: number } | null
): FirebaseFirestore.DocumentData {
  return {
    groupId: base.groupId,
    accountId: base.accountId,
    accountType: base.accountType,
    accountOwnerId: base.accountOwnerId,
    categoryId: base.categoryId,
    payerId: base.payerId,
    createdBy: base.createdBy,
    description: base.description,
    amountCents: toCents(base.amount),
    transactionType: base.transactionType,
    occurredAt,
    isPrivate: base.isPrivate,
    splitType: base.splitType,
    paymentMethod: base.paymentMethod ?? null,
    recurringGroupId: recurring?.groupId ?? null,
    recurringIndex: recurring?.index ?? null,
    recurringTotal: recurring?.total ?? null,
    isSettled: false,
    settlementTransactionId: null,
    securedCardId: base.securedCardId ?? null,
    loanId: base.loanId ?? null,
    transferKind: base.transferKind ?? null,
    goalId: base.goalId ?? null,
    linkKind: base.linkKind ?? null,
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  };
}

// Doc ID = userId within the subcollection -- matches SQL's
// UNIQUE(transaction_id, user_id). groupId/transactionId are denormalized
// onto each split so the balance ledger can collection-group query them.
function writeSplits(writer: Writer, groupId: string, ref: FirebaseFirestore.DocumentReference, splits: SplitInput[]) {
  for (const split of splits) {
    writer.set(ref.collection("splits").doc(split.userId), {
      groupId,
      transactionId: ref.id,
      userId: split.userId,
      shareAmountCents: split.shareAmountCents,
      createdAt: FieldValue.serverTimestamp(),
    });
  }
}

// Lote do Firestore aceita até 500 gravações; acima disso divide em vários.
const BATCH_LIMIT = 450;
async function commitInChunks(ops: ((writer: Writer) => void)[]): Promise<void> {
  for (let start = 0; start < ops.length; start += BATCH_LIMIT) {
    const batch = db.batch();
    ops.slice(start, start + BATCH_LIMIT).forEach((op) => op(batch));
    await batch.commit();
  }
}

export async function insertTransaction(input: NewTransactionInput, splits: SplitInput[] = []): Promise<TransactionRow> {
  const [row] = await insertTransactionSeries(input, [input.occurredAt], splits);
  return row;
}

// Writes every occurrence of a recurring series (or, with a single-element
// `occurredAtDates`, one plain transaction -- insertTransaction above is
// exactly that case) in one batch, each with its own copy of `splits`. Doc
// refs are allocated up front so the first occurrence's id is known before
// the write, which is what every occurrence (including that first one)
// stores as recurringGroupId -- the handle later used to find/cancel "this
// and every future occurrence". Lançamento e divisões vão no mesmo lote:
// nunca fica uma despesa dividida sem as divisões.
export async function insertTransactionSeries(
  base: Omit<NewTransactionInput, "occurredAt">,
  occurredAtDates: string[],
  splits: SplitInput[] = []
): Promise<TransactionRow[]> {
  const refs = occurredAtDates.map(() => transactionsCol.doc());
  const isRecurring = occurredAtDates.length > 1;
  const recurringGroupId = isRecurring ? refs[0].id : null;

  await commitInChunks(
    refs.map((ref, index) => (writer: Writer) => {
      const recurring = recurringGroupId ? { groupId: recurringGroupId, index: index + 1, total: occurredAtDates.length } : null;
      writer.set(ref, transactionData(base, occurredAtDates[index], recurring));
      writeSplits(writer, base.groupId, ref, splits);
    })
  );
  invalidateTransactionReads(base.groupId);

  const docs = await db.getAll(...refs);
  return docs.map(toTransactionRow);
}

// Vários lançamentos soltos (não é uma série) de uma vez, em lotes -- a
// importação de extrato chega a 500 de uma vez.
export async function insertTransactionsBatch(inputs: NewTransactionInput[]): Promise<number> {
  if (inputs.length === 0) return 0;
  await commitInChunks(inputs.map((input) => (writer: Writer) => writer.set(transactionsCol.doc(), transactionData(input, input.occurredAt, null))));
  new Set(inputs.map((input) => input.groupId)).forEach((groupId) => invalidateTransactionReads(groupId));
  return inputs.length;
}

// O mesmo envio de importação duas vezes (clique duplo, rede repetindo) em
// poucos minutos: só o primeiro grava.
const importCommitsCol = db.collection("importCommits");
const IMPORT_DEDUPE_MS = 10 * 60 * 1000;
export async function claimImportCommit(fingerprint: string): Promise<boolean> {
  const ref = importCommitsCol.doc(fingerprint);
  return db.runTransaction(async (t) => {
    const doc = await t.get(ref);
    if (doc.exists && (doc.data()!.at as number) > Date.now() - IMPORT_DEDUPE_MS) return false;
    t.set(ref, { at: Date.now() });
    return true;
  });
}

export async function releaseImportCommit(fingerprint: string): Promise<void> {
  await importCommitsCol.doc(fingerprint).delete();
}

// Pra usar dentro de db.runTransaction: grava um lançamento novo (e as
// divisões) junto com o que mais a transação gravar -- a fatura marcada como
// paga, a parcela, o empréstimo... Ou vai tudo, ou nada. Quem chama invalida
// o cache (invalidateTransactionReads) depois do commit.
export function writeNewTransaction(t: FirebaseFirestore.Transaction, input: NewTransactionInput, splits: SplitInput[] = []): string {
  const ref = transactionsCol.doc();
  t.set(ref, transactionData(input, input.occurredAt, null));
  writeSplits(t, input.groupId, ref, splits);
  return ref.id;
}

// Também dentro de db.runTransaction: lê o lançamento e as divisões (a
// transação do Firestore exige ler tudo antes de gravar) e devolve a função
// que apaga os dois. Lançamento que já não existe: não apaga nada.
export async function prepareTransactionDelete(
  t: FirebaseFirestore.Transaction,
  transactionId: string
): Promise<{ groupId: string | null; apply: () => void }> {
  const ref = transactionsCol.doc(transactionId);
  const [doc, splits] = await Promise.all([t.get(ref), t.get(ref.collection("splits"))]);
  return {
    groupId: doc.exists ? (doc.data()!.groupId as string) : null,
    apply: () => {
      splits.docs.forEach((split) => t.delete(split.ref));
      if (doc.exists) t.delete(ref);
    },
  };
}

// db.runTransaction + limpar o cache de leituras do grupo depois do commit.
export async function runLedgerTransaction<T>(groupId: string, fn: (t: FirebaseFirestore.Transaction) => Promise<T>): Promise<T> {
  const result = await db.runTransaction(fn);
  invalidateTransactionReads(groupId);
  return result;
}

export function transactionDocRef(transactionId: string): FirebaseFirestore.DocumentReference {
  return transactionsCol.doc(transactionId);
}

export { toTransactionRow };

// Every occurrence sharing a recurringGroupId -- a single equality filter,
// no composite index needed. The caller (cancelRecurringForUser) filters
// down to "this one and the future ones" in memory; a series tops out at
// MAX_RECURRENCE_MONTHS (36) rows, cheap either way.
export async function findRecurringSeries(recurringGroupId: string): Promise<TransactionRow[]> {
  const snapshot = await transactionsCol.where("recurringGroupId", "==", recurringGroupId).get();
  return snapshot.docs.map(toTransactionRow);
}

export async function findGoalTransferIds(goalId: string): Promise<string[]> {
  const snapshot = await transactionsCol.where("goalId", "==", goalId).select().get();
  return snapshot.docs.map((doc) => doc.id);
}

export async function findSecuredCardTransferIds(cardId: string): Promise<string[]> {
  const snapshot = await transactionsCol.where("securedCardId", "==", cardId).select().get();
  return snapshot.docs.map((doc) => doc.id);
}

// Lançamentos de antes do linkKind: é o reembolso de alguma despesa dividida?
export async function isSettlementTransaction(transactionId: string): Promise<boolean> {
  const snapshot = await transactionsCol.where("settlementTransactionId", "==", transactionId).limit(1).select().get();
  return !snapshot.empty;
}

// Apaga lançamentos junto com as divisões deles, em lote.
export async function deleteTransactionsBatch(transactionIds: string[]): Promise<void> {
  if (transactionIds.length === 0) return;
  const refs = transactionIds.map((id) => transactionsCol.doc(id));
  const [docs, splitSnaps] = await Promise.all([
    db.getAll(...refs),
    Promise.all(refs.map((ref) => ref.collection("splits").get())),
  ]);
  const ops: ((writer: Writer) => void)[] = [];
  splitSnaps.forEach((snap) => snap.docs.forEach((split) => ops.push((writer) => writer.delete(split.ref))));
  refs.forEach((ref) => ops.push((writer) => writer.delete(ref)));
  await commitInChunks(ops);
  const groupIds = new Set(docs.filter((doc) => doc.exists).map((doc) => doc.data()!.groupId as string));
  groupIds.forEach((groupId) => invalidateTransactionReads(groupId));
}

export async function findTransactionsVisibleTo(
  groupId: string,
  requestingUserId: string,
  limit: number,
  range?: { monthStart: string; monthEnd: string },
  accountId?: string
): Promise<TransactionListRow[]> {
  let jointQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountType", "==", "joint");
  let ownQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountOwnerId", "==", requestingUserId);

  if (accountId) {
    jointQuery = jointQuery.where("accountId", "==", accountId);
    ownQuery = ownQuery.where("accountId", "==", accountId);
  }
  if (range) {
    jointQuery = jointQuery.where("occurredAt", ">=", range.monthStart).where("occurredAt", "<", range.monthEnd);
    ownQuery = ownQuery.where("occurredAt", ">=", range.monthStart).where("occurredAt", "<", range.monthEnd);
  }

  const [jointSnap, ownSnap] = await Promise.all([jointQuery.get(), ownQuery.get()]);
  const seen = new Set<string>();
  const merged = [...jointSnap.docs, ...ownSnap.docs].filter((doc) => {
    if (seen.has(doc.id)) return false;
    seen.add(doc.id);
    return true;
  });

  const categoriesById = await loadCategoriesMap(groupId);

  return merged
    .filter((doc) => {
      const data = doc.data();
      return data.isPrivate === false || data.createdBy === requestingUserId;
    })
    .sort((a, b) => {
      const occurredCompare = (b.data().occurredAt as string).localeCompare(a.data().occurredAt as string);
      if (occurredCompare !== 0) return occurredCompare;
      const aCreated = (a.data().createdAt as FirebaseFirestore.Timestamp | undefined)?.toMillis() ?? 0;
      const bCreated = (b.data().createdAt as FirebaseFirestore.Timestamp | undefined)?.toMillis() ?? 0;
      return bCreated - aCreated;
    })
    .slice(0, limit)
    .map((doc) => {
      const row = toTransactionRow(doc);
      const category = row.categoryId ? categoriesById.get(row.categoryId) : undefined;
      return { ...row, categoryName: category?.name ?? null, categoryEmoji: category?.emoji ?? null };
    });
}

export async function findTransactionById(transactionId: string): Promise<TransactionRow | null> {
  const doc = await transactionsCol.doc(transactionId).get();
  if (!doc.exists) return null;
  return toTransactionRow(doc);
}

export async function deleteTransaction(transactionId: string): Promise<void> {
  await deleteTransactionsBatch([transactionId]);
}

export async function updateTransaction(
  transactionId: string,
  fields: {
    description?: string;
    amount?: number;
    transactionType?: TransactionType;
    categoryId?: string | null;
    occurredAt?: string;
    payerId?: string;
    // null clears it back to "não informado".
    paymentMethod?: PaymentMethod | null;
    // Moving a transaction to a different account also means its
    // accountType/accountOwnerId (denormalized from that account at write
    // time, for the privacy-predicate queries above) must move with it --
    // the service layer resolves the target account and passes all three
    // together, never accountId alone.
    accountId?: string;
    accountType?: "personal" | "joint";
    accountOwnerId?: string | null;
  },
  // undefined: as divisões ficam como estão; uma lista (vazia inclusive):
  // troca todas, no mesmo lote da edição.
  splits?: SplitInput[]
): Promise<TransactionRow> {
  const update: Record<string, unknown> = { updatedAt: FieldValue.serverTimestamp() };
  if (fields.description !== undefined) update.description = fields.description;
  if (fields.amount !== undefined) update.amountCents = toCents(fields.amount);
  if (fields.transactionType !== undefined) update.transactionType = fields.transactionType;
  if (fields.categoryId !== undefined) update.categoryId = fields.categoryId;
  if (fields.occurredAt !== undefined) update.occurredAt = fields.occurredAt;
  if (fields.payerId !== undefined) update.payerId = fields.payerId;
  if (fields.paymentMethod !== undefined) update.paymentMethod = fields.paymentMethod;
  if (fields.accountId !== undefined) update.accountId = fields.accountId;
  if (fields.accountType !== undefined) update.accountType = fields.accountType;
  if (fields.accountOwnerId !== undefined) update.accountOwnerId = fields.accountOwnerId;

  const ref = transactionsCol.doc(transactionId);
  const batch = db.batch();
  batch.update(ref, update);
  if (splits !== undefined) {
    const [current, existing] = await Promise.all([ref.get(), ref.collection("splits").get()]);
    existing.docs.forEach((split) => batch.delete(split.ref));
    if (current.exists) writeSplits(batch, current.data()!.groupId, ref, splits);
  }
  await batch.commit();
  const doc = await ref.get();
  invalidateTransactionReads(doc.data()?.groupId);
  return toTransactionRow(doc);
}

export interface AccountBalanceRow {
  accountId: string;
  balanceCents: number;
}

// Net of income minus expense per account, computed fresh from the
// transaction log each time (no stored running balance -- see schema notes).
export function getAccountBalances(groupId: string): Promise<AccountBalanceRow[]> {
  return memoizeReads(`balances:${groupId}`, () => loadAccountBalances(groupId), groupId);
}

async function loadAccountBalances(groupId: string): Promise<AccountBalanceRow[]> {
  const snapshot = await transactionsCol.where("groupId", "==", groupId).select("accountId", "amountCents", "transactionType").get();
  const balances = new Map<string, number>();
  for (const doc of snapshot.docs) {
    const data = doc.data();
    const delta = data.transactionType === "income" ? data.amountCents : -data.amountCents;
    balances.set(data.accountId, (balances.get(data.accountId) ?? 0) + delta);
  }
  return Array.from(balances.entries()).map(([accountId, balanceCents]) => ({ accountId, balanceCents }));
}

export interface CategorySummaryRow {
  categoryId: string | null;
  categoryName: string | null;
  categoryEmoji: string | null;
  total: string;
}

export interface PayerSummaryRow {
  payerId: string;
  total: string;
}

export type SummaryScope = "joint" | "visible" | "own";

// "joint": only what leaves "Nossa Conta" -- used by the Par page, which is
// specifically about the shared budget.
// "visible": joint + the requester's own personal account -- matches exactly
// what findTransactionsVisibleTo returns, so a page showing both a category
// breakdown and an extrato (Relatórios) never has one contradict the other.
// "own": só a conta pessoal de quem pede -- a mesma base do número do Painel
// e do fechamento do mês, pra "onde mais foi" bater com "saiu".
function fetchExpenseDocsForSummary(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope
): Promise<FirebaseFirestore.QueryDocumentSnapshot[]> {
  return memoizeReads(`summaryDocs:${groupId}:${requestingUserId}:${monthStart}:${monthEnd}:${scope}`, () =>
    loadExpenseDocsForSummary(groupId, requestingUserId, monthStart, monthEnd, scope)
,
    groupId
  );
}

async function loadExpenseDocsForSummary(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope
): Promise<FirebaseFirestore.QueryDocumentSnapshot[]> {
  let jointQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountType", "==", "joint")
    .where("transactionType", "==", "expense")
    .where("occurredAt", ">=", monthStart)
    .where("occurredAt", "<", monthEnd);

  if (scope === "joint") {
    return (await jointQuery.get()).docs;
  }

  const ownQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountOwnerId", "==", requestingUserId)
    .where("transactionType", "==", "expense")
    .where("occurredAt", ">=", monthStart)
    .where("occurredAt", "<", monthEnd);

  if (scope === "own") {
    return (await ownQuery.get()).docs;
  }

  const [jointSnap, ownSnap] = await Promise.all([jointQuery.get(), ownQuery.get()]);
  const seen = new Set<string>();
  return [...jointSnap.docs, ...ownSnap.docs].filter((doc) => {
    if (seen.has(doc.id)) return false;
    seen.add(doc.id);
    return true;
  });
}

export async function getMonthlySummary(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope = "joint"
): Promise<{ byCategory: CategorySummaryRow[]; byPayer: PayerSummaryRow[]; total: string }> {
  const docs = await fetchExpenseDocsForSummary(groupId, requestingUserId, monthStart, monthEnd, scope);

  const categoriesById = await loadCategoriesMap(groupId);

  // Single pass over docs -- byCategory (privacy-gated), byPayer (ungated,
  // see comment below) and the running total all accumulate together instead
  // of three separate traversals of the same array.
  const byCategoryMap = new Map<string, { categoryId: string | null; total: number }>();
  const byPayerMap = new Map<string, number>();
  let totalCents = 0;

  for (const doc of docs) {
    const data = doc.data();
    if (isTransferData(data)) continue;
    totalCents += data.amountCents;
    byPayerMap.set(data.payerId, (byPayerMap.get(data.payerId) ?? 0) + data.amountCents);

    if (data.isPrivate === false || data.createdBy === requestingUserId) {
      const key = data.categoryId ?? "none";
      const entry = byCategoryMap.get(key) ?? { categoryId: data.categoryId ?? null, total: 0 };
      entry.total += data.amountCents;
      byCategoryMap.set(key, entry);
    }
  }
  const byCategory: CategorySummaryRow[] = Array.from(byCategoryMap.values())
    .map((entry) => {
      const category = entry.categoryId ? categoriesById.get(entry.categoryId) : undefined;
      return {
        categoryId: entry.categoryId,
        categoryName: category?.name ?? null,
        categoryEmoji: category?.emoji ?? null,
        total: fromCents(entry.total),
      };
    })
    .sort((a, b) => Number(b.total) - Number(a.total));

  // byPayer intentionally does NOT gate on isPrivate -- matches the original
  // SQL asymmetry (a couple's total spend-by-person is real even if one
  // entry's description is private).
  const byPayer: PayerSummaryRow[] = Array.from(byPayerMap.entries()).map(([payerId, total]) => ({
    payerId,
    total: fromCents(total),
  }));

  return { byCategory, byPayer, total: fromCents(totalCents) };
}

export interface DailySeriesPoint {
  day: string;
  income: string;
  expense: string;
}

// Same query shape as findTransactionsVisibleTo (groupId + accountType/
// accountOwnerId + occurredAt range, no transactionType filter) so it rides
// the composite indexes that already exist for the extrato -- no new index
// needed. Unlike fetchExpenseDocsForSummary this pulls both income and
// expense docs, since the daily series charts both.
function fetchDocsForDateRange(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope
): Promise<FirebaseFirestore.QueryDocumentSnapshot[]> {
  return memoizeReads(`rangeDocs:${groupId}:${requestingUserId}:${monthStart}:${monthEnd}:${scope}`, () =>
    loadDocsForDateRange(groupId, requestingUserId, monthStart, monthEnd, scope)
,
    groupId
  );
}

async function loadDocsForDateRange(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope
): Promise<FirebaseFirestore.QueryDocumentSnapshot[]> {
  let jointQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountType", "==", "joint")
    .where("occurredAt", ">=", monthStart)
    .where("occurredAt", "<", monthEnd);

  if (scope === "joint") {
    return (await jointQuery.get()).docs;
  }

  const ownQuery: FirebaseFirestore.Query = transactionsCol
    .where("groupId", "==", groupId)
    .where("accountOwnerId", "==", requestingUserId)
    .where("occurredAt", ">=", monthStart)
    .where("occurredAt", "<", monthEnd);

  const [jointSnap, ownSnap] = await Promise.all([jointQuery.get(), ownQuery.get()]);
  const seen = new Set<string>();
  return [...jointSnap.docs, ...ownSnap.docs].filter((doc) => {
    if (seen.has(doc.id)) return false;
    seen.add(doc.id);
    return true;
  });
}

export interface OwnRangeDoc {
  month: string;
  amountCents: number;
  transactionType: TransactionType;
  isSecuredCardTransfer: boolean;
  isLoanTransfer: boolean;
  // Guardado numa meta (soma com o guardado no cartão: saiu da conta, é seu).
  isGoalTransfer: boolean;
  // Entre as suas contas: não é receita nem gasto.
  isAccountsTransfer: boolean;
}

// One query across the whole range, personal account only (accountOwnerId,
// not the broader group scope the summary/daily-series queries use) --
// matches exactly what the Painel's hero number ("Você tem no mês") already
// means. Same equality+range field combo as fetchDocsForDateRange's "own"
// branch above, so this reuses an index that already exists instead of
// needing a new composite index deployed.
export function findOwnDocsForRange(
  groupId: string,
  userId: string,
  rangeStart: string,
  rangeEnd: string
): Promise<OwnRangeDoc[]> {
  return memoizeReads(`ownDocs:${groupId}:${userId}:${rangeStart}:${rangeEnd}`, () =>
    loadOwnDocsForRange(groupId, userId, rangeStart, rangeEnd)
,
    groupId
  );
}

async function loadOwnDocsForRange(
  groupId: string,
  userId: string,
  rangeStart: string,
  rangeEnd: string
): Promise<OwnRangeDoc[]> {
  const snapshot = await transactionsCol
    .where("groupId", "==", groupId)
    .where("accountOwnerId", "==", userId)
    .where("occurredAt", ">=", rangeStart)
    .where("occurredAt", "<", rangeEnd)
    .select("occurredAt", "amountCents", "transactionType", "securedCardId", "loanId", "transferKind")
    .get();
  return snapshot.docs.map((doc) => {
    const data = doc.data();
    return {
      month: (data.occurredAt as string).slice(0, 7),
      amountCents: data.amountCents as number,
      transactionType: data.transactionType as TransactionType,
      isSecuredCardTransfer: Boolean(data.securedCardId),
      isLoanTransfer: Boolean(data.loanId),
      isGoalTransfer: data.transferKind === "goal",
      isAccountsTransfer: data.transferKind === "accounts",
    };
  });
}

// Cumulative income/expense per day, from the 1st through the last day of
// the month -- one point per calendar day so the line has no gaps, carrying
// the running total forward on days with no transactions. Always walks the
// whole month, not just up to today: someone who pre-dates a transaction
// later in the current month (a salary or a bill they already know is
// coming on the 5th, entered on the 1st) expects it to count right away --
// stopping at "today" used to silently drop it from every dailyTrend-derived
// widget (the sidebar's Entrada x Saída, the accumulated chart) until the
// calendar caught up to that date, even though the month total elsewhere on
// the same page already included it.
export async function getDailySeries(
  groupId: string,
  requestingUserId: string,
  monthStart: string,
  monthEnd: string,
  scope: SummaryScope = "visible"
): Promise<DailySeriesPoint[]> {
  const docs = await fetchDocsForDateRange(groupId, requestingUserId, monthStart, monthEnd, scope);

  const byDay = new Map<string, { income: number; expense: number }>();
  for (const doc of docs) {
    const data = doc.data();
    if (!(data.isPrivate === false || data.createdBy === requestingUserId)) continue;
    if (isTransferData(data)) continue;
    const entry = byDay.get(data.occurredAt) ?? { income: 0, expense: 0 };
    if (data.transactionType === "income") {
      entry.income += data.amountCents;
    } else {
      entry.expense += data.amountCents;
    }
    byDay.set(data.occurredAt, entry);
  }

  const lastDate = new Date(new Date(`${monthEnd}T00:00:00Z`).getTime() - 86_400_000);

  const points: DailySeriesPoint[] = [];
  let cumIncomeCents = 0;
  let cumExpenseCents = 0;
  for (
    const cursor = new Date(`${monthStart}T00:00:00Z`);
    cursor <= lastDate;
    cursor.setUTCDate(cursor.getUTCDate() + 1)
  ) {
    const day = cursor.toISOString().slice(0, 10);
    const entry = byDay.get(day);
    if (entry) {
      cumIncomeCents += entry.income;
      cumExpenseCents += entry.expense;
    }
    points.push({ day, income: fromCents(cumIncomeCents), expense: fromCents(cumExpenseCents) });
  }
  return points;
}

export interface MonthlyTotalPoint {
  month: string; // "YYYY-MM"
  income: string;
  expense: string;
}

export interface YearlySummary {
  year: number;
  months: MonthlyTotalPoint[];
  totalIncome: string;
  totalExpense: string;
}

// One point per calendar month (Jan-Dec, always all 12 even if some are
// empty) for the whole year -- reuses fetchDocsForDateRange with a
// year-wide range instead of a month-wide one; same composite indexes cover
// both, Firestore doesn't care how wide the range is.
export async function getYearlySummary(
  groupId: string,
  requestingUserId: string,
  year: number,
  scope: SummaryScope = "visible"
): Promise<YearlySummary> {
  const yearStart = `${year}-01-01`;
  const yearEnd = `${year + 1}-01-01`;
  const docs = await fetchDocsForDateRange(groupId, requestingUserId, yearStart, yearEnd, scope);

  const byMonth = new Map<string, { income: number; expense: number }>();
  for (const doc of docs) {
    const data = doc.data();
    if (!(data.isPrivate === false || data.createdBy === requestingUserId)) continue;
    if (isTransferData(data)) continue;
    const monthKey = (data.occurredAt as string).slice(0, 7);
    const entry = byMonth.get(monthKey) ?? { income: 0, expense: 0 };
    if (data.transactionType === "income") {
      entry.income += data.amountCents;
    } else {
      entry.expense += data.amountCents;
    }
    byMonth.set(monthKey, entry);
  }

  let totalIncomeCents = 0;
  let totalExpenseCents = 0;
  const months: MonthlyTotalPoint[] = [];
  for (let month = 1; month <= 12; month++) {
    const monthKey = `${year}-${String(month).padStart(2, "0")}`;
    const entry = byMonth.get(monthKey) ?? { income: 0, expense: 0 };
    totalIncomeCents += entry.income;
    totalExpenseCents += entry.expense;
    months.push({ month: monthKey, income: fromCents(entry.income), expense: fromCents(entry.expense) });
  }

  return { year, months, totalIncome: fromCents(totalIncomeCents), totalExpense: fromCents(totalExpenseCents) };
}

export interface BalanceRow {
  paidBy: string;
  owedBy: string;
  totalOwed: string;
}

// "Who owes whom", computed fresh from transactions+splits (was a SQL VIEW;
// this is the same derivation, just done in Node since Firestore has no
// server-side aggregation).
//
// Deliberately avoids db.collectionGroup("splits") -- that needs a
// COLLECTION_GROUP field-index override (splits.groupId) that isn't
// auto-created and can take a while to build after being deployed the
// first time a query actually needs it, which is exactly what happened the
// first time this got wired into a real screen: production 500s until the
// index finished. Reading each relevant transaction's own splits
// subcollection instead needs no index at all (a subcollection get() is
// always COLLECTION-scoped to its one parent doc) -- N reads instead of 1,
// but N here is "unsettled equal-split expenses in the group", nowhere
// near a scale where that matters for a couple/small-group app.
export function getBalanceRows(groupId: string): Promise<BalanceRow[]> {
  return memoizeReads(`balanceRows:${groupId}`, () => loadBalanceRows(groupId), groupId);
}

async function loadBalanceRows(groupId: string): Promise<BalanceRow[]> {
  const txSnapshot = await transactionsCol
    .where("groupId", "==", groupId)
    .where("transactionType", "==", "expense")
    .select("payerId", "splitType", "isSettled")
    .get();

  // A transaction someone already marked "pago" (settled outside the app --
  // a Pix, cash...), or one that was never split in the first place, has
  // nothing left to contribute here.
  const relevantDocs = txSnapshot.docs.filter((doc) => {
    const data = doc.data();
    return data.splitType && data.splitType !== "none" && !data.isSettled;
  });
  if (relevantDocs.length === 0) return [];

  const splitsSnapshots = await Promise.all(relevantDocs.map((doc) => doc.ref.collection("splits").get()));

  const pairTotals = new Map<string, number>();
  relevantDocs.forEach((doc, index) => {
    const paidBy = doc.data().payerId as string;
    for (const splitDoc of splitsSnapshots[index].docs) {
      const data = splitDoc.data();
      if (data.userId === paidBy) continue;
      const key = `${paidBy}__${data.userId}`;
      pairTotals.set(key, (pairTotals.get(key) ?? 0) + data.shareAmountCents);
    }
  });

  return Array.from(pairTotals.entries()).map(([key, cents]) => {
    const [paidBy, owedBy] = key.split("__");
    return { paidBy, owedBy, totalOwed: fromCents(cents) };
  });
}
